server:
  port: 8080
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false

client:
  applicationName: APP
  url:
    cep: https://viacep.com.br/ws

swagger:
  base-package: com.example.demo
  title: Demo API REST
  description: Documentação do serviço
  version: 1.0
  terms: Terms of Service
  develloper-name: Nome do desenvolvedor
  develloper-email: desenvolvedor@gmail.com
  licence: Apache License Version 2.0
  licence-url: https://www.apache.org/licesen.html